### ISSUE TITLE
Trading212 - Different CSV Format Needs Updating

### ISSUE THREAD

**Issue by Orkan-M** [KapJI/capital-gains-calculator#321]
New columns such as, Stamp duty (GBP), have been introduced into Trading212 CSVs. These new columns are causing ParsingErrors as it is returning with a "Unknown Column"

**Comment by KapJI** [comment]
Thanks for reporting. We need someone who uses Trading212 to submit a PR.

**Comment by Orkssss** [comment]
This is a very useful tool. I wouldn't mind PRing for it. It would save me a lot of time in the future :)

**Comment by vmartinv** [comment]
> This is a very useful tool. I wouldn't mind PRing for it. It would save me a lot of time in the future :)

I don't have such column but I can add support for it. Correct me if I'm wrong but for tax purposes the stamp duty should be counted as a fee right?

**Comment by joe9111** [comment]
I think it should be counted as neither tax nor fees as it is kind of a compulsory charge levied when you buy a UK share: https://www.gov.uk/tax-buy-shares
You need to pay it irrespective of the gain or loss you make when you sell a share.
