### ISSUE TITLE
Error fetching exchange rates from HMRC

### ISSUE THREAD

**Issue by tiziano88** [KapJI/capital-gains-calculator#489]
cgt_calc.exceptions.ParsingError: While parsing http://www.hmrc.gov.uk/softwaredevelopers/rates/exrates-monthly-1012.xml, HMRC API returned a 404 response

Maybe exchange rates are not available for old years?

https://www.trade-tariff.service.gov.uk/exchange_rates/monthly

**Comment by vmartinv** [comment]
which year is failing? I can suggest adding the exchange rates manually to the file until this gets fixed.

**Comment by vmartinv** [comment]
please reopen if you keep having issues

**Comment by tiziano88** [comment]
This is still happening, for year 2013 in the specific.

**Comment by tiziano88** [comment]
Looking around, it seems that maybe those exchange rates are only available from 2014 onwards? https://www.icaew.com/library/research-guides/hmrc-approved-exchange-rates

**Comment by vmartinv** [comment]
If it’s not available the only option left is add the missing rates manually.
