### ISSUE TITLE
Unrealized gains calculation

### ISSUE THREAD

**Issue by vmartinv** [KapJI/capital-gains-calculator#495]
I was thinking it would be useful to have an estimation of unrealized gains for the ongoing years, the way I was thinking of doing this is the following:
- add a `—show-unrealized-gains` flag
- If the flag is set, include it in the final portfolio  (in the console output)
- To calculate the unrealised gains for each symbol fetch the current price (we can use yahoo finance api) and compare it with the calculated pool price. `unrealized gains= current price*quantity-pool price `

Does that sound like something we want to have? I can add a PR for this.

**Comment by KapJI** [comment]
Sounds nice.

Another useful feature could be keeping track of capital gain loss which can be claimed from previous years. If we need to process previous years anyway, it would be useful to display that as well.
