### ISSUE TITLE
Error "texmf-dist-science (no such package)" when building docker image

### ISSUE THREAD

**Issue by jfresen** [KapJI/capital-gains-calculator#530]
In a fresh checkout, I'm following the instructions to run the docker image. But when executing `docker buildx build --platform linux/amd64 --tag capital-gains-calculator .`, I get an error `texmf-dist-science (no such package)`.

I'm not familiar with docker, but from what I can see, the package [doesn't exist on Alpine](https://pkgs.alpinelinux.org/packages?name=texmf-dist-science&branch=edge&repo=&arch=&maintainer=). Should this be fetched from somewhere else?

See [output.txt](https://github.com/user-attachments/files/15687237/output.txt) for the output of the command.

**Comment by azatZul** [comment]
I have the same issue
